version: '3.7'
services:

  redis:
    image: redis:4-alpine
    ports:
      - '6379:6379'

  worker:
    build:
      context: worker
    depends_on:
      - redis
    environment:
      - REDIS_QUEUE=redis
    volumes:
      - ./worker:/app

  queue-wrapper:
    build:
      context: queue-wrapper
    depends_on:
      - redis
    environment:
      - REDIS_QUEUE=redis
    ports:
      - '5000:5000'

  sos:
    container_name: simple-object-storage
    restart: unless-stopped
    build:
      context: simple-object-storage
    ports:
    - '8080:8080'

    depends_on:
      - mongo

    environment:
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_NAME: bucketDB
      DATABASE_USER: jarhan
      DATABASE_PASSWORD: 123456
      AUTHENTICATION_DATABASE: admin

    volumes:
      - './simple-object-storage/data:/app/data'

  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: jarhan
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: bucketDB

    volumes:
    - './simple-object-storage/data/db:/data/db'
    - './simple-object-storage/data/configdb:/data/configdb'

  web:
    build:
      context: web
    ports:
      - '34782:34782'
    depends_on:
      - "queue-wrapper"
