version: '3.7'
services:

  redis:
    image: redis:4-alpine
    ports:
      - '6379:6379'

  worker:
    build:
      context: worker
    depends_on:
      - redis
    environment:
      - REDIS_QUEUE=redis
    volumes:
      - ./worker:/app
    extra_hosts:
      - "sos:172.24.0.1"

  queue-wrapper:
    build:
      context: queue-wrapper
    depends_on:
      - redis
    environment:
      - REDIS_QUEUE=redis
    ports:
      - '5000:5000'

  # sos:
  #   image: jarhan/simple-object-storage
  #   ports:
  #     - '8080:8080'
